import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { ThemeProvider } from "next-themes"
import GlobalToolbar from "@/components/GlobalToolbar"
import { ConversationProvider } from "@/contexts/ConversationContext"

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] })
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"]
})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                    <ConversationProvider>
                        <SidebarProvider>
                            {/* 横向布局：Sidebar | (Toolbar + Page) */}
                            <div className="flex h-screen w-full">
                                {/* ─── 左侧固定 Sidebar ─── */}
                                <AppSidebar />

                                {/* ─── 右侧区域：垂直堆叠 Toolbar + Page ─── */}
                                <div className="flex flex-col flex-1 min-w-0">
                                    <GlobalToolbar />
                                    <main className="flex-1 overflow-hidden">{children}</main>
                                </div>
                            </div>
                        </SidebarProvider>
                    </ConversationProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}
